### ISSUE TITLE
Deobfuscator does not support static methods

### ISSUE THREAD

**Issue by komen205** [giacomoferretti/paranoid-deobfuscator#5] opened 2023-01-18 10:24 UTC
Any obfuscation inside static methods will not be reached, because of the signature. I changed the code and got working a version but still needs improvement. Let me know if you want to see

**Comment by giacomoferretti** [comment] 2023-01-18 10:37
Feel free to open a PR.

Can you also provide an example of the issue?

**Comment by komen205** [comment] 2023-01-18 12:25
I will open a PR.

I will provide an example later this week, basically if you put obfuscated strings in the static construtor, the program will not identify and won't deobfuscate.

**Comment by giacomoferretti** [comment] 2023-01-18 12:57
Input code:
```java
package com.example.java;

import io.michaelrocks.paranoid.Obfuscate;

@Obfuscate
public class Const {
    public static String a;

    static {
        a = "OBFUSCATED";
    }
}
```

Output smali:
```smali
.class public Lcom/example/java/Const;
.super Ljava/lang/Object;
.source "Const.java"


# static fields
.field public static a:Ljava/lang/String;


# direct methods
.method static constructor <clinit>()V
    .registers 2

    .line 10
    const-wide v0, -0x705c9c4adL

    invoke-static {v0, v1}, Lio/michaelrocks/paranoid/Deobfuscator$app$Debug;->getString(J)Ljava/lang/String;

    move-result-object v0

    sput-object v0, Lcom/example/java/Const;->a:Ljava/lang/String;

    .line 11
    return-void
.end method

.method public constructor <init>()V
    .registers 1

    .line 6
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
```

This doesn't match with your PR. Am I doing something wrong?

**Comment by komen205** [comment] 2023-01-18 16:49
```
java.lang.StringBuilder sb = new java.lang.StringBuilder();
sb.append("OBFUSCATED");
```

Should be the problem.

**Comment by giacomoferretti** [comment] 2023-01-18 17:05
```smali
###### Class com.example.java.Const (com.example.java.Const)
.class public Lcom/example/java/Const;
.super Ljava/lang/Object;
.source "Const.java"


# static fields
.field public static a:Ljava/lang/String;


# direct methods
.method static constructor <clinit>()V
    .registers 3

    .line 10
    new-instance v0, Ljava/lang/StringBuilder;

    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V

    .line 11
    .local v0, "sb":Ljava/lang/StringBuilder;
    const-wide v1, -0x70a1b09faL

    invoke-static {v1, v2}, Lio/michaelrocks/paranoid/Deobfuscator$app$Debug;->getString(J)Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 12
    .end local v0    # "sb":Ljava/lang/StringBuilder;
    return-void
.end method

.method public constructor <init>()V
    .registers 1

    .line 6
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
```

The current code is working with this. Not sure where the problem is.

**Comment by giacomoferretti** [comment] 2023-01-18 17:08
Obfuscated:
```java
package com.example.java;

import io.michaelrocks.paranoid.Deobfuscator$app$Debug;

/* loaded from: classes3.dex */
public class Const {
    public static String a;

    static {
        StringBuilder sb = new StringBuilder();
        sb.append(Deobfuscator$app$Debug.getString(-30234315258L));
    }
}
```

Deobfuscated:
```java
package com.example.java;

import io.michaelrocks.paranoid.Deobfuscator$app$Debug;

/* loaded from: classes3.dex */
public class Const {
    public static String a;

    static {
        StringBuilder sb = new StringBuilder();
        Deobfuscator$app$Debug.getString(-30234315258L);
        sb.append("OBFUSCATED");
    }
}
```

It's working fine.

**Comment by giacomoferretti** [comment] 2023-01-24 13:22
I cannot reproduce the bug, can you provide more info, like an example code?

**Comment by giacomoferretti** [comment] 2023-07-05 19:59
I am closing the issue since the issuer has not been heard from since.

Cannot reproduce the bug.

**Closed as completed by giacomoferretti** 2023-07-05 19:59 UTC
Labels: bug, waiting for issuer
